In [ ]:
import pandas as pd
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

In [8]:
df_Clientes = pd.read_csv('./Dados/dados_clientes.csv', sep=',')
df_Clientes.head(10)

   id  idade  renda_anual  pontuacao_gastos
0   1     56        94740                90
1   2     69       136352                50
2   3     46        86617                62
3   4     32       114841                97
4   5     60        36896                51
5   6     25       145729                37
6   7     38        66175                96
7   8     56        27805                87
8   9     36        25237                78
9  10     40       135247                29

In [10]:
df_Clientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                500 non-null    int64
 1   idade             500 non-null    int64
 2   renda_anual       500 non-null    int64
 3   pontuacao_gastos  500 non-null    int64
dtypes: int64(4)
memory usage: 15.8 KB

In [12]:
df_Clientes.describe().round(2)

           id   idade  renda_anual  pontuacao_gastos
count  500.00  500.00       500.00            500.00
mean   250.50   44.73     81557.17             48.51
std    144.48   15.24     36764.38             29.56
min      1.00   18.00     20384.00              0.00
25%    125.75   32.00     49172.75             24.00
50%    250.50   45.00     79219.00             48.50
75%    375.25   57.00    113017.25             73.25
max    500.00   70.00    149695.00            100.00

In [14]:
padronizador = StandardScaler() #padroniza deixa mesma escala
df_Clientes_padronizado = padronizador.fit_transform(df_Clientes[['idade', 'renda_anual', 'pontuacao_gastos']])
print(df_Clientes_padronizado[:10])

[[ 0.74012478  0.35893538  1.40506904]
 [ 1.59401387  1.49192537  0.05039391]
 [ 0.08328703  0.13776654  0.45679645]
 [-0.83628583  0.906235    1.64213719]
 [ 1.00285989 -1.2160111   0.08426079]
 [-1.29607226  1.74723747 -0.3898755 ]
 [-0.44218318 -0.41881765  1.60827031]
 [ 0.74012478 -1.46353615  1.30346841]
 [-0.57355073 -1.53345632  0.9986665 ]
 [-0.31081563  1.461839   -0.66081053]]

In [ ]:
k = 3 #número de clusters
kmeans = KMeans(n_clusters=k) #cria o modelo KMeans com k clusters
kmeans.fit(df_Clientes_padronizado) #ajusta o modelo aos dados padronizados
df_Clientes['cluster'] = kmeans.labels_ #adiciona os rótulos dos clusters ao DataFrame original

c:\Users\LUCAS\anaconda3\Lib\site-packages\sklearn\cluster\_kmeans.py:1429: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=2.
  warnings.warn(

In [17]:
df_Clientes.head(10)

   id  idade  renda_anual  pontuacao_gastos  cluster
0   1     56        94740                90        0
1   2     69       136352                50        0
2   3     46        86617                62        0
3   4     32       114841                97        0
4   5     60        36896                51        1
5   6     25       145729                37        2
6   7     38        66175                96        0
7   8     56        27805                87        1
8   9     36        25237                78        1
9  10     40       135247                29        2

In [27]:
df_Clientes.to_csv('./Dados/dados_clientes_clusters.csv', sep=',', index=False)

In [23]:
#!pip install powerbiclient

In [24]:
from powerbiclient import QuickVisualize, get_dataset_config, Report
from powerbiclient.authentication import DeviceCodeLoginAuthentication

In [35]:
Define_auth = DeviceCodeLoginAuthentication()

Performing device flow authentication. Please follow the instructions below.
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code AUANWGSRS to authenticate.

Device flow authentication successfully completed.
You are now logged in .

The result should be passed only to trusted code in your notebook.

In [38]:
# Carregar o CSV como DataFrame
df = pd.read_csv('./Dados/dados_clientes_clusters.csv')

# Obter a configuração do dataset
dataset_config = get_dataset_config(df)

# Visualizar com autenticação definida
Relatorio_PBI = QuickVisualize(dataset_config, auth=Define_auth)

In [39]:
Relatorio_PBI

QuickVisualize()